blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/FrancescoCastaldi/BenzaTracker/discussions
    about: Please ask and answer questions here.
  - name: Security Policy
    url: https://github.com/FrancescoCastaldi/BenzaTracker/security/policy
    about: Please report security vulnerabilities here.
