name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Before submitting, please search [existing issues](https://github.com/FrancescoCastaldi/BenzaTracker/issues)
        to see if this has already been discussed.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What alternatives have you considered?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, examples from other projects?
